/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tictactoe;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        TicTacToe game = new TicTacToe();

        game.printBoard();
        while (!game.checkVictory()) {
            Scanner in = new Scanner(System.in);
            if (game.currentPlayer == TicTacToe.X) {
                long startTime = System.currentTimeMillis();
                TicTacToe.Move move=null;
                for (int i=0; i<60;i++) {
                    //move = game.getBestMoveRecursive();
                    move = game.clone().getBestMove();
                }
                System.out.println("The bot took " + ((System.currentTimeMillis() - startTime)/60) + " ms to calculate its move");
                game.makeMove(move.x, move.y);
            } else {
                System.out.print("[" + game.currentPlayer + "] Input X for new move: ");
                int x = in.nextInt();
                System.out.print("[" + game.currentPlayer + "] Input Y for new move: ");
                int y = in.nextInt();
                try {
                    game.makeMove(x, y);
                } catch (Exception ex) {
                    System.err.println(ex.getMessage());
                    System.err.println("Please try again...");
                }
            }
            System.out.println();
            game.printBoard();
        }
        System.out.println(game.currentPlayer + " WON!");
    }
}
